version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
  api-server:
    build: backend
    ports:
      - "8080:8080"
  ml:
    build: ml
    ports:
      - "50051"

volumes:
  pgdata: