version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: dev
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  database:
    build:
      context: backend
      args:
        SERVICE: database
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_SCHEMA: dev
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_GRPCPORT: 3333
    ports:
      - "3333"
    depends_on:
      - postgres

  mail:
    build:
      context: backend
      args:
        SERVICE: mail
        COPY_PATH: ./templates
    environment:
      MAIL_AMQPSERVERURL: amqp://user:password@rabbitmq:5672/
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_LOGIN: root@localhost
      MAIL_PASSWORD: root
    depends_on:
      - rabbitmq

  api:
    build:
      context: backend
      args:
        SERVICE: api
    ports:
      - "8080:8080"
    depends_on:
      - database
      - mail
      - ml

  ml:
    build: ml
    ports:
      - "50051"

volumes:
  pgdata:
  rabbitmq_data: